
EVALUATOR:
    BATCH_SIZE_PER_GPU: &bs 10
    MAX_DISP: &max_disp 192
    METRIC:
        - d1_all
        - epe
        - thres_1
        - thres_2
        - thres_3


TESTING:
    BATCH_SIZE_PER_GPU: *bs
    MAX_DISP: *max_disp
    METRIC:
        - d1_all
        - epe
        - thres_1
        - thres_2
        - thres_3