DATA_CONFIG:
    DATA_INFOS:
        -   DATASET: SceneFlowDataset
            DATA_SPLIT: {
                # TRAINING: ./data/SceneFlow/sceneflow_finalpass_train.txt,
                # EVALUATING: ./data/SceneFlow/sceneflow_finalpass_test.txt,
                # TESTING: ./data/SceneFlow/sceneflow_finalpass_test.txt
                TRAINING: D:\OneDrive\OneDrive - Univerza v Ljubljani\datasets\sceneflow\sceneflow_finalpass_train_dev.txt,
                EVALUATING: D:\OneDrive\OneDrive - Univerza v Ljubljani\datasets\sceneflow\sceneflow_finalpass_valid_dev.txt,
                TESTING: D:\OneDrive\OneDrive - Univerza v Ljubljani\datasets\sceneflow\sceneflow_finalpass_test_dev.txt
            }
            # DATA_PATH: D:\OneDrive\OneDrive - Univerza v Ljubljani\datasets\sceneflow
            DATA_PATH: D:\OneDrive\OneDrive - Univerza v Ljubljani\datasets\sceneflow
            RETURN_RIGHT_DISP: false

OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 2